### ISSUE TITLE
How to use with Vite?

### ISSUE THREAD

**Issue by fluxxus** [mathiasbno/three-starmap#1]
Hi! I am trying to add your package on top of a simple Vite/Three.js configuration, but it results in bunch of errors. I've installed `vite-plugin-glsl` to help with loading custom shaders.

The simple starter files are from Bruno Simon's Three.js journey course. As a matter of fact I first saw `three-starmap` in the course Discord channel when you posted it. 

My guess is that I am doing something wrong, so here I am :)

Edit: The same errors are present when using esm.sh(CDN for es6 modules)
[https://esm.sh/three-starmap@0.0.2](https://esm.sh/three-starmap@0.0.2)
```
/* esm.sh - error */
throw new Error("[esm.sh] " + "esbuild: No loader is configured for \".glsl\" files: ../esmd/npm/three-starmap@0.0.2/node_modules/.pnpm/three-starmap@0.0.2/node_modules/three-starmap/src/shader/vertex.glsl");
export default null;
```

**Comment by mathiasbno** [comment]
Apologies for the late reply. 

I have done some small bugfixes for some potential problems and updated my code to use Vite as well. So feel free to update to the latest version.

I found that adding the following to vite.config.js will solve this issue:

```js
…
optimizeDeps: {
  esbuildOptions: {
    loader: {
      ".glsl": "text",
    },
  },
}
…
```

Hope it helps :)
